=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class ApiVersion
    N2025_12_08 = "2025-12-08".freeze
    N2025_10_27 = "2025-10-27".freeze
    N2023_01_05 = "2023-01-05".freeze
    N2022_09_01 = "2022-09-01".freeze
    N2021_08_18 = "2021-08-18".freeze
    N2021_07_05 = "2021-07-05".freeze
    N2021_02_21 = "2021-02-21".freeze
    N2020_05_18 = "2020-05-18".freeze

    def self.all_vars
      @all_vars ||= [N2025_12_08, N2025_10_27, N2023_01_05, N2022_09_01, N2021_08_18, N2021_07_05, N2021_02_21, N2020_05_18].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ApiVersion.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ApiVersion"
    end
  end
end
