=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class CreateAnInquiryRequestMeta < ApiModelBase
    # If true, automatically create an Account for the user if one does not exist. Default is true.
    attr_accessor :auto_create_account

    # If `auto-create-account` is true, the type ID to use for the Account. If not provided, the default type ID for the organization will be used. If `auto-create-account-reference-id` is present and corresponds to an existing Account, `auto-create-account-type-id` will be ignored. Will error if passed when `auto-create-account` is false.
    attr_accessor :auto_create_account_type_id

    # If `auto-create-account` is true, this Inquiry will be attached to the Account with this reference ID, or a new Account will be created with this reference ID if one does not exist. Will error if passed when `auto-create-account` is false.
    attr_accessor :auto_create_account_reference_id

    # If true, automatically create an Inquiry Session token for the Inquiry.
    attr_accessor :auto_create_inquiry_session

    # If true, automatically create a One-Time Link URL for the Inquiry.
    attr_accessor :auto_create_one_time_link

    # Time interval from inquiry creation after which an Inquiry expires and the flow can no longer be accessed. Overrides value set at the template level.
    attr_accessor :expiration_after_create_interval_seconds

    # Time interval from inquiry start after which an Inquiry expires and the flow can no longer be accessed. Overrides value set at the template level.
    attr_accessor :expiration_after_start_interval_seconds

    # Time interval from inquiry start after which an Inquiry expires and the flow can no longer be accessed. Overrides value set at the template level.
    attr_accessor :expiration_after_resume_interval_seconds

    # Time interval after which Device Handoff one time links expire. Overrides value set at the template level.
    attr_accessor :one_time_link_expiration_seconds

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'auto_create_account' => :'auto-create-account',
        :'auto_create_account_type_id' => :'auto-create-account-type-id',
        :'auto_create_account_reference_id' => :'auto-create-account-reference-id',
        :'auto_create_inquiry_session' => :'auto-create-inquiry-session',
        :'auto_create_one_time_link' => :'auto-create-one-time-link',
        :'expiration_after_create_interval_seconds' => :'expiration-after-create-interval-seconds',
        :'expiration_after_start_interval_seconds' => :'expiration-after-start-interval-seconds',
        :'expiration_after_resume_interval_seconds' => :'expiration-after-resume-interval-seconds',
        :'one_time_link_expiration_seconds' => :'one-time-link-expiration-seconds'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'auto_create_account' => :'Boolean',
        :'auto_create_account_type_id' => :'String',
        :'auto_create_account_reference_id' => :'String',
        :'auto_create_inquiry_session' => :'Boolean',
        :'auto_create_one_time_link' => :'Boolean',
        :'expiration_after_create_interval_seconds' => :'Integer',
        :'expiration_after_start_interval_seconds' => :'Integer',
        :'expiration_after_resume_interval_seconds' => :'Integer',
        :'one_time_link_expiration_seconds' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'expiration_after_create_interval_seconds',
        :'expiration_after_start_interval_seconds',
        :'expiration_after_resume_interval_seconds',
        :'one_time_link_expiration_seconds'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::CreateAnInquiryRequestMeta` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::CreateAnInquiryRequestMeta`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'auto_create_account')
        self.auto_create_account = attributes[:'auto_create_account']
      end

      if attributes.key?(:'auto_create_account_type_id')
        self.auto_create_account_type_id = attributes[:'auto_create_account_type_id']
      end

      if attributes.key?(:'auto_create_account_reference_id')
        self.auto_create_account_reference_id = attributes[:'auto_create_account_reference_id']
      end

      if attributes.key?(:'auto_create_inquiry_session')
        self.auto_create_inquiry_session = attributes[:'auto_create_inquiry_session']
      end

      if attributes.key?(:'auto_create_one_time_link')
        self.auto_create_one_time_link = attributes[:'auto_create_one_time_link']
      end

      if attributes.key?(:'expiration_after_create_interval_seconds')
        self.expiration_after_create_interval_seconds = attributes[:'expiration_after_create_interval_seconds']
      end

      if attributes.key?(:'expiration_after_start_interval_seconds')
        self.expiration_after_start_interval_seconds = attributes[:'expiration_after_start_interval_seconds']
      end

      if attributes.key?(:'expiration_after_resume_interval_seconds')
        self.expiration_after_resume_interval_seconds = attributes[:'expiration_after_resume_interval_seconds']
      end

      if attributes.key?(:'one_time_link_expiration_seconds')
        self.one_time_link_expiration_seconds = attributes[:'one_time_link_expiration_seconds']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          auto_create_account == o.auto_create_account &&
          auto_create_account_type_id == o.auto_create_account_type_id &&
          auto_create_account_reference_id == o.auto_create_account_reference_id &&
          auto_create_inquiry_session == o.auto_create_inquiry_session &&
          auto_create_one_time_link == o.auto_create_one_time_link &&
          expiration_after_create_interval_seconds == o.expiration_after_create_interval_seconds &&
          expiration_after_start_interval_seconds == o.expiration_after_start_interval_seconds &&
          expiration_after_resume_interval_seconds == o.expiration_after_resume_interval_seconds &&
          one_time_link_expiration_seconds == o.one_time_link_expiration_seconds
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [auto_create_account, auto_create_account_type_id, auto_create_account_reference_id, auto_create_inquiry_session, auto_create_one_time_link, expiration_after_create_interval_seconds, expiration_after_start_interval_seconds, expiration_after_resume_interval_seconds, one_time_link_expiration_seconds].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
