=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  module Importer
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'ImporterAccount',
          :'ImporterListItemEmailAddress',
          :'ImporterListItemField',
          :'ImporterListItemGeolocation',
          :'ImporterListItemGovernmentIdNumber',
          :'ImporterListItemIpAddress',
          :'ImporterListItemName',
          :'ImporterListItemPhoneNumber'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'type'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'importer/account' => :'ImporterAccount',
          :'importer/list-item/email-address' => :'ImporterListItemEmailAddress',
          :'importer/list-item/field' => :'ImporterListItemField',
          :'importer/list-item/geolocation' => :'ImporterListItemGeolocation',
          :'importer/list-item/government-id-number' => :'ImporterListItemGovernmentIdNumber',
          :'importer/list-item/ip-address' => :'ImporterListItemIpAddress',
          :'importer/list-item/name' => :'ImporterListItemName',
          :'importer/list-item/phone-number' => :'ImporterListItemPhoneNumber'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        PersonaAPIClient.const_get(klass).build_from_hash(data)
      end
    end
  end

end
