=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class InquiryTemplateAttributes < ApiModelBase
    # Name of the Inquiry Template
    attr_accessor :name

    # Possible values: - active - inactive  Do not assume this is a static enumeration; Persona may add new values in the future without a versioned update.
    attr_accessor :status

    # List of domains allowed for embedded flows
    attr_accessor :embedded_flow_domain_allowlist

    # The subdomain that your hosted flow can be hosted on (e.g. \"mycompany.withpersona.com\")
    attr_accessor :hosted_flow_subdomains

    # An allowlist that specifies the URI schemes for redirect after completion of a Hosted Flow. This can be used to implement deep linking for mobile integrations. If this list is empty, all URLs with the URI scheme http or https are allowed.
    attr_accessor :hosted_flow_redirect_uri_schemes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'status' => :'status',
        :'embedded_flow_domain_allowlist' => :'embedded-flow-domain-allowlist',
        :'hosted_flow_subdomains' => :'hosted-flow-subdomains',
        :'hosted_flow_redirect_uri_schemes' => :'hosted-flow-redirect-uri-schemes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'status' => :'String',
        :'embedded_flow_domain_allowlist' => :'Array<String>',
        :'hosted_flow_subdomains' => :'Array<String>',
        :'hosted_flow_redirect_uri_schemes' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::InquiryTemplateAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::InquiryTemplateAttributes`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'embedded_flow_domain_allowlist')
        if (value = attributes[:'embedded_flow_domain_allowlist']).is_a?(Array)
          self.embedded_flow_domain_allowlist = value
        end
      end

      if attributes.key?(:'hosted_flow_subdomains')
        if (value = attributes[:'hosted_flow_subdomains']).is_a?(Array)
          self.hosted_flow_subdomains = value
        end
      end

      if attributes.key?(:'hosted_flow_redirect_uri_schemes')
        if (value = attributes[:'hosted_flow_redirect_uri_schemes']).is_a?(Array)
          self.hosted_flow_redirect_uri_schemes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          status == o.status &&
          embedded_flow_domain_allowlist == o.embedded_flow_domain_allowlist &&
          hosted_flow_subdomains == o.hosted_flow_subdomains &&
          hosted_flow_redirect_uri_schemes == o.hosted_flow_redirect_uri_schemes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, status, embedded_flow_domain_allowlist, hosted_flow_subdomains, hosted_flow_redirect_uri_schemes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
