=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class InquiryAttributesBehaviors < ApiModelBase
    # Number of requests from restricted API versions
    attr_accessor :api_version_less_than_minimum_count

    attr_accessor :autofill_cancels

    # Number of times the user autofilled a form field.
    attr_accessor :autofill_starts

    # A predictive, proprietary score you can use to assess fraud risk. This score is created by Persona and based on a combination of behavioral signals.
    attr_accessor :behavior_threat_level

    # A score between 0 and 100 that indicates the likelihood that the user is a bot.
    attr_accessor :bot_score

    # Time duration of user interaction.
    attr_accessor :completion_time

    attr_accessor :devtools_open

    # A debugger was detected within a mobile integration flow.
    attr_accessor :debugger_attached

    # Number of times the user switched focus from the flow for browser-based integrations.
    attr_accessor :distraction_events

    attr_accessor :hesitation_baseline

    # Number of periods where the user made no inputs.
    attr_accessor :hesitation_count

    # Percentage of time in the flow where the user made no inputs.
    attr_accessor :hesitation_percentage

    # Total time where the user made no inputs.
    attr_accessor :hesitation_time

    # Number of requests from restricted mobile SDK versions
    attr_accessor :mobile_sdk_version_less_than_minimum_count

    # Number of requests that were likely spoofed.
    attr_accessor :request_spoof_attempts

    # Number of times the user used a keyboard shortcut to copy information.
    attr_accessor :shortcut_copies

    # Number of times the user used a keyboard shortcut to paste information.
    attr_accessor :shortcut_pastes

    # Number of user agent headers that were likely spoofed on seen devices
    attr_accessor :user_agent_spoof_attempts

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'api_version_less_than_minimum_count' => :'api-version-less-than-minimum-count',
        :'autofill_cancels' => :'autofill-cancels',
        :'autofill_starts' => :'autofill-starts',
        :'behavior_threat_level' => :'behavior-threat-level',
        :'bot_score' => :'bot-score',
        :'completion_time' => :'completion-time',
        :'devtools_open' => :'devtools-open',
        :'debugger_attached' => :'debugger-attached',
        :'distraction_events' => :'distraction-events',
        :'hesitation_baseline' => :'hesitation-baseline',
        :'hesitation_count' => :'hesitation-count',
        :'hesitation_percentage' => :'hesitation-percentage',
        :'hesitation_time' => :'hesitation-time',
        :'mobile_sdk_version_less_than_minimum_count' => :'mobile-sdk-version-less-than-minimum-count',
        :'request_spoof_attempts' => :'request-spoof-attempts',
        :'shortcut_copies' => :'shortcut-copies',
        :'shortcut_pastes' => :'shortcut-pastes',
        :'user_agent_spoof_attempts' => :'user-agent-spoof-attempts'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'api_version_less_than_minimum_count' => :'Integer',
        :'autofill_cancels' => :'Integer',
        :'autofill_starts' => :'Integer',
        :'behavior_threat_level' => :'String',
        :'bot_score' => :'Integer',
        :'completion_time' => :'Float',
        :'devtools_open' => :'Boolean',
        :'debugger_attached' => :'Boolean',
        :'distraction_events' => :'Integer',
        :'hesitation_baseline' => :'Integer',
        :'hesitation_count' => :'Integer',
        :'hesitation_percentage' => :'Float',
        :'hesitation_time' => :'Integer',
        :'mobile_sdk_version_less_than_minimum_count' => :'Integer',
        :'request_spoof_attempts' => :'Integer',
        :'shortcut_copies' => :'Integer',
        :'shortcut_pastes' => :'Integer',
        :'user_agent_spoof_attempts' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'api_version_less_than_minimum_count',
        :'autofill_cancels',
        :'autofill_starts',
        :'behavior_threat_level',
        :'bot_score',
        :'completion_time',
        :'devtools_open',
        :'debugger_attached',
        :'distraction_events',
        :'hesitation_baseline',
        :'hesitation_count',
        :'hesitation_percentage',
        :'hesitation_time',
        :'mobile_sdk_version_less_than_minimum_count',
        :'request_spoof_attempts',
        :'shortcut_copies',
        :'shortcut_pastes',
        :'user_agent_spoof_attempts'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::InquiryAttributesBehaviors` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::InquiryAttributesBehaviors`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'api_version_less_than_minimum_count')
        self.api_version_less_than_minimum_count = attributes[:'api_version_less_than_minimum_count']
      else
        self.api_version_less_than_minimum_count = 0
      end

      if attributes.key?(:'autofill_cancels')
        self.autofill_cancels = attributes[:'autofill_cancels']
      else
        self.autofill_cancels = 0
      end

      if attributes.key?(:'autofill_starts')
        self.autofill_starts = attributes[:'autofill_starts']
      else
        self.autofill_starts = 0
      end

      if attributes.key?(:'behavior_threat_level')
        self.behavior_threat_level = attributes[:'behavior_threat_level']
      end

      if attributes.key?(:'bot_score')
        self.bot_score = attributes[:'bot_score']
      else
        self.bot_score = 0
      end

      if attributes.key?(:'completion_time')
        self.completion_time = attributes[:'completion_time']
      else
        self.completion_time = 0
      end

      if attributes.key?(:'devtools_open')
        self.devtools_open = attributes[:'devtools_open']
      else
        self.devtools_open = true
      end

      if attributes.key?(:'debugger_attached')
        self.debugger_attached = attributes[:'debugger_attached']
      else
        self.debugger_attached = false
      end

      if attributes.key?(:'distraction_events')
        self.distraction_events = attributes[:'distraction_events']
      else
        self.distraction_events = 0
      end

      if attributes.key?(:'hesitation_baseline')
        self.hesitation_baseline = attributes[:'hesitation_baseline']
      else
        self.hesitation_baseline = 0
      end

      if attributes.key?(:'hesitation_count')
        self.hesitation_count = attributes[:'hesitation_count']
      else
        self.hesitation_count = 0
      end

      if attributes.key?(:'hesitation_percentage')
        self.hesitation_percentage = attributes[:'hesitation_percentage']
      else
        self.hesitation_percentage = 0
      end

      if attributes.key?(:'hesitation_time')
        self.hesitation_time = attributes[:'hesitation_time']
      else
        self.hesitation_time = 0
      end

      if attributes.key?(:'mobile_sdk_version_less_than_minimum_count')
        self.mobile_sdk_version_less_than_minimum_count = attributes[:'mobile_sdk_version_less_than_minimum_count']
      else
        self.mobile_sdk_version_less_than_minimum_count = 0
      end

      if attributes.key?(:'request_spoof_attempts')
        self.request_spoof_attempts = attributes[:'request_spoof_attempts']
      else
        self.request_spoof_attempts = 0
      end

      if attributes.key?(:'shortcut_copies')
        self.shortcut_copies = attributes[:'shortcut_copies']
      else
        self.shortcut_copies = 0
      end

      if attributes.key?(:'shortcut_pastes')
        self.shortcut_pastes = attributes[:'shortcut_pastes']
      else
        self.shortcut_pastes = 0
      end

      if attributes.key?(:'user_agent_spoof_attempts')
        self.user_agent_spoof_attempts = attributes[:'user_agent_spoof_attempts']
      else
        self.user_agent_spoof_attempts = 0
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          api_version_less_than_minimum_count == o.api_version_less_than_minimum_count &&
          autofill_cancels == o.autofill_cancels &&
          autofill_starts == o.autofill_starts &&
          behavior_threat_level == o.behavior_threat_level &&
          bot_score == o.bot_score &&
          completion_time == o.completion_time &&
          devtools_open == o.devtools_open &&
          debugger_attached == o.debugger_attached &&
          distraction_events == o.distraction_events &&
          hesitation_baseline == o.hesitation_baseline &&
          hesitation_count == o.hesitation_count &&
          hesitation_percentage == o.hesitation_percentage &&
          hesitation_time == o.hesitation_time &&
          mobile_sdk_version_less_than_minimum_count == o.mobile_sdk_version_less_than_minimum_count &&
          request_spoof_attempts == o.request_spoof_attempts &&
          shortcut_copies == o.shortcut_copies &&
          shortcut_pastes == o.shortcut_pastes &&
          user_agent_spoof_attempts == o.user_agent_spoof_attempts
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [api_version_less_than_minimum_count, autofill_cancels, autofill_starts, behavior_threat_level, bot_score, completion_time, devtools_open, debugger_attached, distraction_events, hesitation_baseline, hesitation_count, hesitation_percentage, hesitation_time, mobile_sdk_version_less_than_minimum_count, request_spoof_attempts, shortcut_copies, shortcut_pastes, user_agent_spoof_attempts].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
