=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner < ApiModelBase
    # The datetime when the entry was ignored.
    attr_accessor :ignored_at

    # The datetime when the run history was completed.
    attr_accessor :run_history_completed_at

    attr_accessor :match

    # The user who added the entry to the ignore list.
    attr_accessor :user

    # The reason why the entry was added to the ignore list.
    attr_accessor :ignore_reason

    # Indicates if the ignore list entry is internal.
    attr_accessor :is_internal

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ignored_at' => :'ignored-at',
        :'run_history_completed_at' => :'run-history-completed-at',
        :'match' => :'match',
        :'user' => :'user',
        :'ignore_reason' => :'ignore-reason',
        :'is_internal' => :'is-internal'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ignored_at' => :'Time',
        :'run_history_completed_at' => :'Time',
        :'match' => :'ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInnerMatch',
        :'user' => :'String',
        :'ignore_reason' => :'String',
        :'is_internal' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ignored_at')
        self.ignored_at = attributes[:'ignored_at']
      end

      if attributes.key?(:'run_history_completed_at')
        self.run_history_completed_at = attributes[:'run_history_completed_at']
      end

      if attributes.key?(:'match')
        self.match = attributes[:'match']
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'ignore_reason')
        self.ignore_reason = attributes[:'ignore_reason']
      end

      if attributes.key?(:'is_internal')
        self.is_internal = attributes[:'is_internal']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ignored_at == o.ignored_at &&
          run_history_completed_at == o.run_history_completed_at &&
          match == o.match &&
          user == o.user &&
          ignore_reason == o.ignore_reason &&
          is_internal == o.is_internal
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ignored_at, run_history_completed_at, match, user, ignore_reason, is_internal].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
