=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class ReportProfileRequestAttributesAllOfQuery < ApiModelBase
    # The first name of the individual to search.
    attr_accessor :name_first

    # The last name of the individual to search.
    attr_accessor :name_last

    # The birthdate of the individual, formatted as YYYY-MM-DD (ISO 8601).
    attr_accessor :birthdate

    # Social security number.
    attr_accessor :social_security_number

    # Address line 1 (e.g., street or PO Box).
    attr_accessor :address_street_1

    # Address line 2 (e.g., apartment, suite, unit, or building).
    attr_accessor :address_street_2

    # City of residence.
    attr_accessor :address_city

    # State or subdivision of residence, unabbreviated.
    attr_accessor :address_subdivision

    # ZIP or postal code of residence.
    attr_accessor :address_postal_code

    # ISO 3166-1 alpha-2 country code for the location of residence.
    attr_accessor :country_code

    # Phone number.
    attr_accessor :phone_number

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name_first' => :'name-first',
        :'name_last' => :'name-last',
        :'birthdate' => :'birthdate',
        :'social_security_number' => :'social-security-number',
        :'address_street_1' => :'address-street-1',
        :'address_street_2' => :'address-street-2',
        :'address_city' => :'address-city',
        :'address_subdivision' => :'address-subdivision',
        :'address_postal_code' => :'address-postal-code',
        :'country_code' => :'country-code',
        :'phone_number' => :'phone-number'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name_first' => :'String',
        :'name_last' => :'String',
        :'birthdate' => :'String',
        :'social_security_number' => :'String',
        :'address_street_1' => :'String',
        :'address_street_2' => :'String',
        :'address_city' => :'String',
        :'address_subdivision' => :'String',
        :'address_postal_code' => :'String',
        :'country_code' => :'String',
        :'phone_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name_first',
        :'name_last',
        :'birthdate',
        :'social_security_number',
        :'address_street_1',
        :'address_street_2',
        :'address_city',
        :'address_subdivision',
        :'address_postal_code',
        :'country_code',
        :'phone_number'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::ReportProfileRequestAttributesAllOfQuery` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::ReportProfileRequestAttributesAllOfQuery`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name_first')
        self.name_first = attributes[:'name_first']
      end

      if attributes.key?(:'name_last')
        self.name_last = attributes[:'name_last']
      end

      if attributes.key?(:'birthdate')
        self.birthdate = attributes[:'birthdate']
      end

      if attributes.key?(:'social_security_number')
        self.social_security_number = attributes[:'social_security_number']
      end

      if attributes.key?(:'address_street_1')
        self.address_street_1 = attributes[:'address_street_1']
      end

      if attributes.key?(:'address_street_2')
        self.address_street_2 = attributes[:'address_street_2']
      end

      if attributes.key?(:'address_city')
        self.address_city = attributes[:'address_city']
      end

      if attributes.key?(:'address_subdivision')
        self.address_subdivision = attributes[:'address_subdivision']
      end

      if attributes.key?(:'address_postal_code')
        self.address_postal_code = attributes[:'address_postal_code']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if !@birthdate.nil? && @birthdate !~ pattern
        invalid_properties.push("invalid value for \"birthdate\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^\d{3}-\d{2}-\d{4}$/)
      if !@social_security_number.nil? && @social_security_number !~ pattern
        invalid_properties.push("invalid value for \"social_security_number\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@birthdate.nil? && @birthdate !~ Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      return false if !@social_security_number.nil? && @social_security_number !~ Regexp.new(/^\d{3}-\d{2}-\d{4}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] birthdate Value to be assigned
    def birthdate=(birthdate)
      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if !birthdate.nil? && birthdate !~ pattern
        fail ArgumentError, "invalid value for \"birthdate\", must conform to the pattern #{pattern}."
      end

      @birthdate = birthdate
    end

    # Custom attribute writer method with validation
    # @param [Object] social_security_number Value to be assigned
    def social_security_number=(social_security_number)
      pattern = Regexp.new(/^\d{3}-\d{2}-\d{4}$/)
      if !social_security_number.nil? && social_security_number !~ pattern
        fail ArgumentError, "invalid value for \"social_security_number\", must conform to the pattern #{pattern}."
      end

      @social_security_number = social_security_number
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name_first == o.name_first &&
          name_last == o.name_last &&
          birthdate == o.birthdate &&
          social_security_number == o.social_security_number &&
          address_street_1 == o.address_street_1 &&
          address_street_2 == o.address_street_2 &&
          address_city == o.address_city &&
          address_subdivision == o.address_subdivision &&
          address_postal_code == o.address_postal_code &&
          country_code == o.country_code &&
          phone_number == o.phone_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name_first, name_last, birthdate, social_security_number, address_street_1, address_street_2, address_city, address_subdivision, address_postal_code, country_code, phone_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
