=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class VerificationGovernmentIdAttributes < ApiModelBase
    # The status of the verification  Possible values: - initiated - submitted - passed - failed - requires_retry - canceled - confirmed  Do not assume this is a static enumeration; Persona may add new values in the future without a versioned update.
    attr_accessor :status

    # The time the verification was created in ISO 8601 format
    attr_accessor :created_at

    # The time the verification was created in Unix timestamp format
    attr_accessor :created_at_ts

    # The time the verification was submitted in ISO 8601 format
    attr_accessor :submitted_at

    # The time the verification was submitted in Unix timestamp format
    attr_accessor :submitted_at_ts

    # The time the verification was completed in ISO 8601 format
    attr_accessor :completed_at

    # The time the verification was completed in Unix timestamp format
    attr_accessor :completed_at_ts

    # The time the verification was redacted in ISO 8601 format
    attr_accessor :redacted_at

    # ISO 3166-1 alpha 2 country code.
    attr_accessor :country_code

    # Tags on the verification
    attr_accessor :tags

    attr_accessor :checks

    # Street name of residence address.
    attr_accessor :address_street_1

    # Extension of residence address, usually apartment or suite number.
    attr_accessor :address_street_2

    # City of residence address. Not all international addresses use this attribute.
    attr_accessor :address_city

    # State or subdivision of residence address. In the US, this should be the unabbreviated name. Not all international addresses use this attribute.
    attr_accessor :address_subdivision

    # ZIP or postal code of residence address. Not all international addresses use this attribute.
    attr_accessor :address_postal_code

    attr_accessor :entity_confidence_reasons

    attr_accessor :entity_confidence_score

    attr_accessor :front_photo_url

    attr_accessor :back_photo_url

    attr_accessor :photo_urls

    attr_accessor :selfie_photo

    attr_accessor :selfie_photo_url

    attr_accessor :video_url

    attr_accessor :id_class

    attr_accessor :capture_method

    attr_accessor :name_first

    attr_accessor :name_middle

    attr_accessor :name_last

    attr_accessor :name_suffix

    # Native script given or first name.
    attr_accessor :native_name_first

    # Native script middle name.
    attr_accessor :native_name_middle

    # Native script family or last name.
    attr_accessor :native_name_last

    # Native script name title or prefix.
    attr_accessor :native_name_title

    attr_accessor :birthdate

    attr_accessor :issuing_authority

    attr_accessor :issuing_subdivision

    attr_accessor :nationality

    attr_accessor :document_number

    attr_accessor :visa_status

    attr_accessor :issue_date

    attr_accessor :expiration_date

    attr_accessor :designations

    attr_accessor :birthplace

    attr_accessor :endorsements

    attr_accessor :height

    attr_accessor :sex

    attr_accessor :restrictions

    attr_accessor :vehicle_class

    attr_accessor :identification_number

    attr_accessor :from_reusable_persona

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'status' => :'status',
        :'created_at' => :'created-at',
        :'created_at_ts' => :'created-at-ts',
        :'submitted_at' => :'submitted-at',
        :'submitted_at_ts' => :'submitted-at-ts',
        :'completed_at' => :'completed-at',
        :'completed_at_ts' => :'completed-at-ts',
        :'redacted_at' => :'redacted-at',
        :'country_code' => :'country-code',
        :'tags' => :'tags',
        :'checks' => :'checks',
        :'address_street_1' => :'address-street-1',
        :'address_street_2' => :'address-street-2',
        :'address_city' => :'address-city',
        :'address_subdivision' => :'address-subdivision',
        :'address_postal_code' => :'address-postal-code',
        :'entity_confidence_reasons' => :'entity-confidence-reasons',
        :'entity_confidence_score' => :'entity-confidence-score',
        :'front_photo_url' => :'front-photo-url',
        :'back_photo_url' => :'back-photo-url',
        :'photo_urls' => :'photo-urls',
        :'selfie_photo' => :'selfie-photo',
        :'selfie_photo_url' => :'selfie-photo-url',
        :'video_url' => :'video-url',
        :'id_class' => :'id-class',
        :'capture_method' => :'capture-method',
        :'name_first' => :'name-first',
        :'name_middle' => :'name-middle',
        :'name_last' => :'name-last',
        :'name_suffix' => :'name-suffix',
        :'native_name_first' => :'native-name-first',
        :'native_name_middle' => :'native-name-middle',
        :'native_name_last' => :'native-name-last',
        :'native_name_title' => :'native-name-title',
        :'birthdate' => :'birthdate',
        :'issuing_authority' => :'issuing-authority',
        :'issuing_subdivision' => :'issuing-subdivision',
        :'nationality' => :'nationality',
        :'document_number' => :'document-number',
        :'visa_status' => :'visa-status',
        :'issue_date' => :'issue-date',
        :'expiration_date' => :'expiration-date',
        :'designations' => :'designations',
        :'birthplace' => :'birthplace',
        :'endorsements' => :'endorsements',
        :'height' => :'height',
        :'sex' => :'sex',
        :'restrictions' => :'restrictions',
        :'vehicle_class' => :'vehicle-class',
        :'identification_number' => :'identification-number',
        :'from_reusable_persona' => :'from-reusable-persona'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'status' => :'String',
        :'created_at' => :'Time',
        :'created_at_ts' => :'Integer',
        :'submitted_at' => :'Time',
        :'submitted_at_ts' => :'Integer',
        :'completed_at' => :'Time',
        :'completed_at_ts' => :'Integer',
        :'redacted_at' => :'Time',
        :'country_code' => :'String',
        :'tags' => :'Array<String>',
        :'checks' => :'Array<VerificationSharedAttributesChecksInner>',
        :'address_street_1' => :'String',
        :'address_street_2' => :'String',
        :'address_city' => :'String',
        :'address_subdivision' => :'String',
        :'address_postal_code' => :'String',
        :'entity_confidence_reasons' => :'Array<String>',
        :'entity_confidence_score' => :'Float',
        :'front_photo_url' => :'String',
        :'back_photo_url' => :'String',
        :'photo_urls' => :'Array<VerificationGovernmentIdAttributesAllOfPhotoUrlsInner>',
        :'selfie_photo' => :'VerificationGovernmentIdAttributesAllOfSelfiePhoto',
        :'selfie_photo_url' => :'String',
        :'video_url' => :'String',
        :'id_class' => :'String',
        :'capture_method' => :'String',
        :'name_first' => :'String',
        :'name_middle' => :'String',
        :'name_last' => :'String',
        :'name_suffix' => :'String',
        :'native_name_first' => :'String',
        :'native_name_middle' => :'String',
        :'native_name_last' => :'String',
        :'native_name_title' => :'String',
        :'birthdate' => :'String',
        :'issuing_authority' => :'String',
        :'issuing_subdivision' => :'String',
        :'nationality' => :'String',
        :'document_number' => :'String',
        :'visa_status' => :'String',
        :'issue_date' => :'String',
        :'expiration_date' => :'String',
        :'designations' => :'Array<Object>',
        :'birthplace' => :'String',
        :'endorsements' => :'String',
        :'height' => :'String',
        :'sex' => :'String',
        :'restrictions' => :'String',
        :'vehicle_class' => :'String',
        :'identification_number' => :'String',
        :'from_reusable_persona' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'entity_confidence_score',
        :'front_photo_url',
        :'back_photo_url',
        :'photo_urls',
        :'selfie_photo_url',
        :'video_url',
        :'id_class',
        :'capture_method',
        :'name_first',
        :'name_middle',
        :'name_last',
        :'name_suffix',
        :'native_name_first',
        :'native_name_middle',
        :'native_name_last',
        :'native_name_title',
        :'birthdate',
        :'issuing_authority',
        :'issuing_subdivision',
        :'nationality',
        :'document_number',
        :'visa_status',
        :'issue_date',
        :'expiration_date',
        :'designations',
        :'birthplace',
        :'endorsements',
        :'height',
        :'sex',
        :'restrictions',
        :'vehicle_class',
        :'identification_number',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'AddressFields',
      :'VerificationSharedAttributes'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::VerificationGovernmentIdAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::VerificationGovernmentIdAttributes`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'created_at_ts')
        self.created_at_ts = attributes[:'created_at_ts']
      end

      if attributes.key?(:'submitted_at')
        self.submitted_at = attributes[:'submitted_at']
      end

      if attributes.key?(:'submitted_at_ts')
        self.submitted_at_ts = attributes[:'submitted_at_ts']
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      end

      if attributes.key?(:'completed_at_ts')
        self.completed_at_ts = attributes[:'completed_at_ts']
      end

      if attributes.key?(:'redacted_at')
        self.redacted_at = attributes[:'redacted_at']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'checks')
        if (value = attributes[:'checks']).is_a?(Array)
          self.checks = value
        end
      end

      if attributes.key?(:'address_street_1')
        self.address_street_1 = attributes[:'address_street_1']
      end

      if attributes.key?(:'address_street_2')
        self.address_street_2 = attributes[:'address_street_2']
      end

      if attributes.key?(:'address_city')
        self.address_city = attributes[:'address_city']
      end

      if attributes.key?(:'address_subdivision')
        self.address_subdivision = attributes[:'address_subdivision']
      end

      if attributes.key?(:'address_postal_code')
        self.address_postal_code = attributes[:'address_postal_code']
      end

      if attributes.key?(:'entity_confidence_reasons')
        if (value = attributes[:'entity_confidence_reasons']).is_a?(Array)
          self.entity_confidence_reasons = value
        end
      end

      if attributes.key?(:'entity_confidence_score')
        self.entity_confidence_score = attributes[:'entity_confidence_score']
      else
        self.entity_confidence_score = 0
      end

      if attributes.key?(:'front_photo_url')
        self.front_photo_url = attributes[:'front_photo_url']
      end

      if attributes.key?(:'back_photo_url')
        self.back_photo_url = attributes[:'back_photo_url']
      end

      if attributes.key?(:'photo_urls')
        if (value = attributes[:'photo_urls']).is_a?(Array)
          self.photo_urls = value
        end
      end

      if attributes.key?(:'selfie_photo')
        self.selfie_photo = attributes[:'selfie_photo']
      end

      if attributes.key?(:'selfie_photo_url')
        self.selfie_photo_url = attributes[:'selfie_photo_url']
      end

      if attributes.key?(:'video_url')
        self.video_url = attributes[:'video_url']
      end

      if attributes.key?(:'id_class')
        self.id_class = attributes[:'id_class']
      end

      if attributes.key?(:'capture_method')
        self.capture_method = attributes[:'capture_method']
      end

      if attributes.key?(:'name_first')
        self.name_first = attributes[:'name_first']
      end

      if attributes.key?(:'name_middle')
        self.name_middle = attributes[:'name_middle']
      end

      if attributes.key?(:'name_last')
        self.name_last = attributes[:'name_last']
      end

      if attributes.key?(:'name_suffix')
        self.name_suffix = attributes[:'name_suffix']
      end

      if attributes.key?(:'native_name_first')
        self.native_name_first = attributes[:'native_name_first']
      end

      if attributes.key?(:'native_name_middle')
        self.native_name_middle = attributes[:'native_name_middle']
      end

      if attributes.key?(:'native_name_last')
        self.native_name_last = attributes[:'native_name_last']
      end

      if attributes.key?(:'native_name_title')
        self.native_name_title = attributes[:'native_name_title']
      end

      if attributes.key?(:'birthdate')
        self.birthdate = attributes[:'birthdate']
      end

      if attributes.key?(:'issuing_authority')
        self.issuing_authority = attributes[:'issuing_authority']
      end

      if attributes.key?(:'issuing_subdivision')
        self.issuing_subdivision = attributes[:'issuing_subdivision']
      end

      if attributes.key?(:'nationality')
        self.nationality = attributes[:'nationality']
      end

      if attributes.key?(:'document_number')
        self.document_number = attributes[:'document_number']
      end

      if attributes.key?(:'visa_status')
        self.visa_status = attributes[:'visa_status']
      end

      if attributes.key?(:'issue_date')
        self.issue_date = attributes[:'issue_date']
      end

      if attributes.key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      end

      if attributes.key?(:'designations')
        if (value = attributes[:'designations']).is_a?(Array)
          self.designations = value
        end
      end

      if attributes.key?(:'birthplace')
        self.birthplace = attributes[:'birthplace']
      end

      if attributes.key?(:'endorsements')
        self.endorsements = attributes[:'endorsements']
      end

      if attributes.key?(:'height')
        self.height = attributes[:'height']
      end

      if attributes.key?(:'sex')
        self.sex = attributes[:'sex']
      end

      if attributes.key?(:'restrictions')
        self.restrictions = attributes[:'restrictions']
      end

      if attributes.key?(:'vehicle_class')
        self.vehicle_class = attributes[:'vehicle_class']
      end

      if attributes.key?(:'identification_number')
        self.identification_number = attributes[:'identification_number']
      end

      if attributes.key?(:'from_reusable_persona')
        self.from_reusable_persona = attributes[:'from_reusable_persona']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          status == o.status &&
          created_at == o.created_at &&
          created_at_ts == o.created_at_ts &&
          submitted_at == o.submitted_at &&
          submitted_at_ts == o.submitted_at_ts &&
          completed_at == o.completed_at &&
          completed_at_ts == o.completed_at_ts &&
          redacted_at == o.redacted_at &&
          country_code == o.country_code &&
          tags == o.tags &&
          checks == o.checks &&
          address_street_1 == o.address_street_1 &&
          address_street_2 == o.address_street_2 &&
          address_city == o.address_city &&
          address_subdivision == o.address_subdivision &&
          address_postal_code == o.address_postal_code &&
          entity_confidence_reasons == o.entity_confidence_reasons &&
          entity_confidence_score == o.entity_confidence_score &&
          front_photo_url == o.front_photo_url &&
          back_photo_url == o.back_photo_url &&
          photo_urls == o.photo_urls &&
          selfie_photo == o.selfie_photo &&
          selfie_photo_url == o.selfie_photo_url &&
          video_url == o.video_url &&
          id_class == o.id_class &&
          capture_method == o.capture_method &&
          name_first == o.name_first &&
          name_middle == o.name_middle &&
          name_last == o.name_last &&
          name_suffix == o.name_suffix &&
          native_name_first == o.native_name_first &&
          native_name_middle == o.native_name_middle &&
          native_name_last == o.native_name_last &&
          native_name_title == o.native_name_title &&
          birthdate == o.birthdate &&
          issuing_authority == o.issuing_authority &&
          issuing_subdivision == o.issuing_subdivision &&
          nationality == o.nationality &&
          document_number == o.document_number &&
          visa_status == o.visa_status &&
          issue_date == o.issue_date &&
          expiration_date == o.expiration_date &&
          designations == o.designations &&
          birthplace == o.birthplace &&
          endorsements == o.endorsements &&
          height == o.height &&
          sex == o.sex &&
          restrictions == o.restrictions &&
          vehicle_class == o.vehicle_class &&
          identification_number == o.identification_number &&
          from_reusable_persona == o.from_reusable_persona
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [status, created_at, created_at_ts, submitted_at, submitted_at_ts, completed_at, completed_at_ts, redacted_at, country_code, tags, checks, address_street_1, address_street_2, address_city, address_subdivision, address_postal_code, entity_confidence_reasons, entity_confidence_score, front_photo_url, back_photo_url, photo_urls, selfie_photo, selfie_photo_url, video_url, id_class, capture_method, name_first, name_middle, name_last, name_suffix, native_name_first, native_name_middle, native_name_last, native_name_title, birthdate, issuing_authority, issuing_subdivision, nationality, document_number, visa_status, issue_date, expiration_date, designations, birthplace, endorsements, height, sex, restrictions, vehicle_class, identification_number, from_reusable_persona].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
