# # INSTRUCTIONS FOR UPDATING GEM
#
# Updating this gem is pretty straightforward, but it has a few gotchas.
# Follow the instructions below in sequence.
#
# ## 1. Update the configuration
#
# Take a look at the configuration file (that's the file you're
# currently looking at) to see if anything needs to change. If you're
# regenerating, you probably want to bump the version number, at least.
#
# ## 2. Update the OpenAPI spec
#
# Download the latest `openapi-bundled.yml` file from
# https://github.com/persona-id/persona-openapi. Save it to the
# top-level directory as `openapi-bundled.yml`. You can use a command
# like this:
#
#     curl -LO https://github.com/persona-id/persona-openapi/raw/refs/heads/main/2025-12-08/openapi-bundled.yaml
#
# But I recommend actually visiting the repository and ensuring you're
# getting the most up to date version.
#
# ## 3. Hack the discriminator specification for included objects
#
# You need to hack the spec to work around a bug in `openapi-generator`.
# The specific bug is very subtle. You won't notice it when you generate
# the code, and it will all load and run. But you'll get the incorrect
# types for certain objects.
#
# The bug seems to be that the generator doesn't properly use the `type`
# field as a discriminator for `anyOf` schemas. With `anyOf`, instead of
# producing code that identifies the correct type unambiguously using
# the `type` field, it instead produces code that tries each possible
# schema in order, returning the first match from a list of types. Since
# the lists of types are alphabetized, this means it finds the wrong
# type in cases where the actual type we want is further down the
# alphabet (e.g., `Selfie` versus `VerificationSelfie`).
#
# Luckily, using `oneOf` instead of `anyOf` generators code with a
# discriminator that uses the `type` field. We can just make this change
# throughout the spec as a workaround for the problem.
#
# To apply the workaround, run:
#
#     sed -i '' 's/anyOf:/oneOf:/' openapi-bundled.yaml
#
# ## 4. Hack the file schema type to reference `file` first
#
# You need to hack the spec one more time to work around another bug in
# `openapi-generator`. This is another case that is very difficult to
# notice.
#
# The explanation is rather complicated, but basically, the order of
# types for the file schema gives `null` first in the list of types. In
# an older version of the spec, this wasn't a problem because `null` was
# a specifically defined object. In the newer version, the `null` object
# schema got removed, exposing this bug. Therefore, we need to make sure
# that the `file` type comes first in that list.
#
# To apply the workaround, run:
#
#     sed -i '' "/^    file:$/,/^    [a-z]/{
#       s/- 'null'/- TEMP_NULL/
#       s/- object/- 'null'/
#       s/- TEMP_NULL/- object/
#     }" openapi-bundled.yaml
#
# ## 5. Delete the old code
#
# Next, remove all the old generated code:
#
#     rm -rf *.gem docs lib spec Gemfile Gemfile.lock persona_api_client.gemspec
#
# You'll want to do this so that files that are no longer generated
# don't accidentally hang around.
#
# ## 5. Regenerate the code
#
# Run the following to regenerate the project:
#
#     openapi-generator generate --config openapi_generator_config.yml
#
# ## 6. Finish
#
# Now you can commit for review.

inputSpec: openapi-bundled.yaml
generatorName: ruby
output: .
additionalProperties:
  gemName: "persona_api_client"
  gemAuthor: "Hey Jane"
  gemAuthorEmail: "eng_product@heyjane.co"
  gemLicense: "MIT"
  gemRequiredRubyVersion: ">= 3.0"
  gemVersion: "2.0.3"
  library: "faraday"
  moduleName: "PersonaAPIClient"
  useAutoload: true
