=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PersonaAPIClient::InquiryTemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InquiryTemplatesApi' do
  before do
    # run before each test
    @api_instance = PersonaAPIClient::InquiryTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InquiryTemplatesApi' do
    it 'should create an instance of InquiryTemplatesApi' do
      expect(@api_instance).to be_instance_of(PersonaAPIClient::InquiryTemplatesApi)
    end
  end

  # unit tests for list_all_inquiry_templates
  # List all Inquiry Templates
  # Retrieves a list of your organization&#39;s Inquiry Templates.  Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like Inquiry Templates in Sandbox via API. Results are returned in reverse chronological order, with the most recently created objects first.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [ListAllAccountsPageParameter] :page 
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [ListAllInquiryTemplates200Response]
  describe 'list_all_inquiry_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_an_inquiry_template
  # Retrieve an Inquiry Template
  # Retrieves details of a specific Inquiry Template by ID.  Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like Inquiry Templates in Sandbox via API.
  # @param inquiry_template_id Inquiry Template ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [RetrieveAnInquiryTemplate200Response]
  describe 'retrieve_an_inquiry_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
