=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PersonaAPIClient::InquiriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InquiriesApi' do
  before do
    # run before each test
    @api_instance = PersonaAPIClient::InquiriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InquiriesApi' do
    it 'should create an instance of InquiriesApi' do
      expect(@api_instance).to be_instance_of(PersonaAPIClient::InquiriesApi)
    end
  end

  # unit tests for approve_an_inquiry
  # Approve an Inquiry
  # Approves an Inquiry.  Note that this action will trigger any associated workflows and webhooks.  Approving an inquiry will prevent further progress on the inquiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [ApproveAnInquiryRequest] :approve_an_inquiry_request 
  # @return [RedactAnInquiry200Response]
  describe 'approve_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_an_inquiry
  # Create an Inquiry
  # Creates a new inquiry with optional pre-filled attributes.  See [Sessions](https://docs.withpersona.com/inquiry-sessions) for how to continue the inquiry in [Embedded Flow](https://docs.withpersona.com/embedded-flow) or [Hosted Flow](https://docs.withpersona.com/hosted-flow).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [CreateAnInquiryRequest] :create_an_inquiry_request 
  # @return [CreateAnInquiry201Response]
  describe 'create_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for decline_an_inquiry
  # Decline an Inquiry
  # Declines an Inquiry.  Note that this action will trigger any associated workflows and webhooks.  Declining an inquiry will prevent further progress on the inquiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [ApproveAnInquiryRequest] :approve_an_inquiry_request 
  # @return [RedactAnInquiry200Response]
  describe 'decline_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for expire_an_inquiry
  # Expire an Inquiry
  # Expires an Inquiry and all sessions on the Inquiry. Cancels any pending Verifications on the inquiry.  The Inquiry can still be resumed after expiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [RedactAnInquiry200Response]
  describe 'expire_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for generate_a_one_time_link
  # Generate a one-time link for an Inquiry
  # Creates a new inquiry session and returns &#x60;meta.one-time-link&#x60;.
  # @param inquiry_id Inquiry ID (starts with \&quot;inq_\&quot;)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [GenerateAOneTimeLinkRequest] :generate_a_one_time_link_request 
  # @return [GenerateAOneTimeLink200Response]
  describe 'generate_a_one_time_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for inquiries_add_tag
  # Add tag to an Inquiry
  # Adds a new tag to an Inquiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [InquiriesAddTagRequest] :inquiries_add_tag_request 
  # @return [RedactAnInquiry200Response]
  describe 'inquiries_add_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for inquiries_perform_simulate_actions
  # Perform Simulate Actions
  # Performs a series of simulated actions on a Sandbox Inquiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [InquiriesPerformSimulateActionsRequest] :inquiries_perform_simulate_actions_request 
  # @return [RedactAnInquiry200Response]
  describe 'inquiries_perform_simulate_actions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for inquiries_remove_tag
  # Remove tag from an Inquiry
  # Removes an existing tag from an Inquiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [InquiriesAddTagRequest] :inquiries_add_tag_request 
  # @return [RedactAnInquiry200Response]
  describe 'inquiries_remove_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for inquiries_set_all_tags
  # Set tags on an Inquiry
  # Sets all tags on an Inquiry. Any tags that are not provided in the request will be removed.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [InquiriesSetAllTagsRequest] :inquiries_set_all_tags_request 
  # @return [RedactAnInquiry200Response]
  describe 'inquiries_set_all_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_inquiries
  # List all Inquiries
  # Returns a list of your organization&#39;s inquiries.  Note that this endpoint aggregates inquiries across all inquiry template(s). See [Pagination](https://docs.withpersona.com/pagination) for more details about handling the response. Results are returned in reverse chronological order, with the most recently created objects first.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [ListAllAccountsPageParameter] :page 
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [ListAllInquiriesFilterParameter] :filter 
  # @return [ListAllInquiries200Response]
  describe 'list_all_inquiries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_an_inquiry_for_review
  # Mark an Inquiry for manual review
  # Marks an Inquiry for manual review. Inquiries that are already approved or declined cannot be marked for review.  Note that this action will trigger any associated workflows and webhooks.  Marking an inquiry for review will prevent further progress on the inquiry.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [RedactAnInquiry200Response]
  describe 'mark_an_inquiry_for_review test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for print_an_inquiry_pdf
  # Print Inquiry PDF
  # Prints an Inquiry as PDF.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @return [Null]
  describe 'print_an_inquiry_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redact_an_inquiry
  # Redact an Inquiry
  # Permanently deletes personally identifiable information (PII) for an Inquiry and all associated Verifications, Reports, or other Persona resources. The response indicates a successful redaction of the Inquiry. Redaction of the Inquiry&#39;s associated child objects are done asynchronously and may take some time before all associated child objects are fully redacted. **This action cannot be undone**.  This endpoint can be used to comply with privacy regulations such as GDPR / CCPA or to enforce data privacy.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [RedactAnInquiry200Response]
  describe 'redact_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for resume_an_inquiry
  # Resume an Inquiry
  # Creates a session token that is returned as &#x60;meta.session-token&#x60;. If the inquiry&#39;s status is &#x60;expired&#x60;, changes the status to &#x60;pending&#x60;. The &#x60;session-token&#x60; must be included when loading the inquiry flow if the inquiry&#39;s status is &#x60;pending&#x60;. This endpoint will error if the inquiry is redacted. This endpoint first tries to reuse any existing valid unused [sessions](https://docs.withpersona.com/inquiry-sessions). If none exist, a new session is created. For more information, see [Resuming Inquiries](https://docs.withpersona.com/resuming-inquiries).
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [ResumeAnInquiry200Response]
  describe 'resume_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_an_inquiry
  # Retrieve an Inquiry
  # Retrieves the details of an existing Inquiry.  In the [Embedded Flow](https://docs.withpersona.com/embedded-flow), the &#x60;inquiry-id&#x60; is the first parameter of the onStart callback. In the [Hosted Flow](https://docs.withpersona.com/hosted-flow), the &#x60;inquiry-id&#x60; is a query parameter in the onComplete callback.  Template information will be found in &#x60;data.relationships.inquiry-template&#x60; if the inquiry is a Dynamic Flow inquiry, and in &#x60;data.relationships.template&#x60; if the inquiry is a Legacy 2.0 inquiry. For more information, see [Dynamic Flow vs. Legacy Templates](https://docs.withpersona.com/inquiry-templates#dynamic-flow-vs-legacy-templates).
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @return [RetrieveAnInquiry200Response]
  describe 'retrieve_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_an_inquiry
  # Update an Inquiry
  # Updates an existing Inquiry.  Note that if you use webhooks, updates to inquiries that are not in progress can result in data getting out of sync. For example, updating a completed Inquiry will not cause your Inquiry completed webhook to retrigger.  Inquiries represent a snapshot of data collected from an individual, so we generally do not recommend updating an Inquiry&#39;s data after the Inquiry has been finalized.
  # @param inquiry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response.
  # @option opts [String] :idempotency_key Ensures the request is idempotent.
  # @option opts [ApiVersion] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
  # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
  # @option opts [UpdateAnInquiryRequest] :update_an_inquiry_request 
  # @return [RedactAnInquiry200Response]
  describe 'update_an_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
