=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PersonaAPIClient::WebhooksInquiryEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksInquiryEventsApi' do
  before do
    # run before each test
    @api_instance = PersonaAPIClient::WebhooksInquiryEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksInquiryEventsApi' do
    it 'should create an instance of WebhooksInquiryEventsApi' do
      expect(@api_instance).to be_instance_of(PersonaAPIClient::WebhooksInquiryEventsApi)
    end
  end

  # unit tests for webhook_inquiry_approved
  # Inquiry approved
  # Webhook for the &#x60;inquiry.approved&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_approved test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_completed
  # Inquiry completed
  # Webhook for the &#x60;inquiry.completed&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_completed test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_created
  # Inquiry created
  # Webhook for the &#x60;inquiry.created&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryCreatedRequest] :webhook_inquiry_created_request 
  # @return [nil]
  describe 'webhook_inquiry_created test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_declined
  # Inquiry declined
  # Webhook for the &#x60;inquiry.declined&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_declined test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_expired
  # Inquiry expired
  # Webhook for the &#x60;inquiry.expired&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_expired test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_failed
  # Inquiry failed
  # Webhook for the &#x60;inquiry.failed&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_failed test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_marked_for_review
  # Inquiry marked for review
  # Webhook for the &#x60;inquiry.marked-for-review&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_marked_for_review test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_inquiry_transitioned
  # Inquiry transitioned
  # Webhook for the &#x60;inquiry.transitioned&#x60; event. For more info see [Webhooks Overview](https://docs.withpersona.com/webhooks).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :persona_signature Header. An HMAC that you should use to check that requests are authentic. Compare this value with your own digest, computed from the request body and your webhook secret. For more info see [Webhook Best Practices](https://docs.withpersona.com/webhooks-best-practices).
  # @option opts [Integer] :persona_webhook_attempts_made The number of times that Persona has attempted to deliver this webhook. This value is incremented each time Persona attempts to deliver the webhook, regardless of whether the delivery was successful.
  # @option opts [Integer] :persona_webhook_attempts_left The number of times that Persona will attempt to deliver this webhook. This value is decremented each time Persona attempts to deliver the webhook.
  # @option opts [Integer] :persona_webhook_first_attempted_at The time at which Persona first attempted to deliver this webhook. This value is a Unix timestamp in seconds.
  # @option opts [WebhookInquiryExpiredRequest] :webhook_inquiry_expired_request 
  # @return [nil]
  describe 'webhook_inquiry_transitioned test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
