=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PersonaAPIClient::InlineObject4ErrorsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PersonaAPIClient::InlineObject4ErrorsInner do
  #let(:instance) { PersonaAPIClient::InlineObject4ErrorsInner.new }

  describe 'test an instance of InlineObject4ErrorsInner' do
    it 'should create an instance of InlineObject4ErrorsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PersonaAPIClient::InlineObject4ErrorsInner)
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
