=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PersonaAPIClient::ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PersonaAPIClient::ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner do
  #let(:instance) { PersonaAPIClient::ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner.new }

  describe 'test an instance of ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner' do
    it 'should create an instance of ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PersonaAPIClient::ReportPoliticallyExposedPersonAttributesAllOfIgnoreListInner)
    end
  end

  describe 'test attribute "ignored_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "run_history_completed_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "match"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ignore_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_internal"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
