=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PersonaAPIClient::UpdateATransactionRequestData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PersonaAPIClient::UpdateATransactionRequestData do
  #let(:instance) { PersonaAPIClient::UpdateATransactionRequestData.new }

  describe 'test an instance of UpdateATransactionRequestData' do
    it 'should create an instance of UpdateATransactionRequestData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PersonaAPIClient::UpdateATransactionRequestData)
    end
  end

  describe 'test attribute "attributes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
