=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2025-12-08
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'cgi'

module PersonaAPIClient
  class InquiryTemplatesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List all Inquiry Templates
    # Retrieves a list of your organization's Inquiry Templates.  Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like Inquiry Templates in Sandbox via API. Results are returned in reverse chronological order, with the most recently created objects first.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :key_inflection Determines casing for the API response.
    # @option opts [String] :idempotency_key Ensures the request is idempotent.
    # @option opts [ApiVersion] :persona_version 
    # @option opts [ListAllAccountsPageParameter] :page 
    # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
    # @return [ListAllInquiryTemplates200Response]
    def list_all_inquiry_templates(opts = {})
      data, _status_code, _headers = list_all_inquiry_templates_with_http_info(opts)
      data
    end

    # List all Inquiry Templates
    # Retrieves a list of your organization&#39;s Inquiry Templates.  Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like Inquiry Templates in Sandbox via API. Results are returned in reverse chronological order, with the most recently created objects first.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :key_inflection Determines casing for the API response.
    # @option opts [String] :idempotency_key Ensures the request is idempotent.
    # @option opts [ApiVersion] :persona_version 
    # @option opts [ListAllAccountsPageParameter] :page 
    # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
    # @return [Array<(ListAllInquiryTemplates200Response, Integer, Hash)>] ListAllInquiryTemplates200Response data, response status code and response headers
    def list_all_inquiry_templates_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: InquiryTemplatesApi.list_all_inquiry_templates ...'
      end
      allowable_values = ["camel", "kebab", "snake"]
      if @api_client.config.client_side_validation && opts[:'key_inflection'] && !allowable_values.include?(opts[:'key_inflection'])
        fail ArgumentError, "invalid value for \"key_inflection\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/inquiry-templates'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'fields'] = opts[:'fields'] if !opts[:'fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'Key-Inflection'] = opts[:'key_inflection'] if !opts[:'key_inflection'].nil?
      header_params[:'Idempotency-Key'] = opts[:'idempotency_key'] if !opts[:'idempotency_key'].nil?
      header_params[:'Persona-Version'] = opts[:'persona_version'] if !opts[:'persona_version'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListAllInquiryTemplates200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"InquiryTemplatesApi.list_all_inquiry_templates",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: InquiryTemplatesApi#list_all_inquiry_templates\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve an Inquiry Template
    # Retrieves details of a specific Inquiry Template by ID.  Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like Inquiry Templates in Sandbox via API.
    # @param inquiry_template_id [String] Inquiry Template ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :key_inflection Determines casing for the API response.
    # @option opts [String] :idempotency_key Ensures the request is idempotent.
    # @option opts [ApiVersion] :persona_version 
    # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
    # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
    # @return [RetrieveAnInquiryTemplate200Response]
    def retrieve_an_inquiry_template(inquiry_template_id, opts = {})
      data, _status_code, _headers = retrieve_an_inquiry_template_with_http_info(inquiry_template_id, opts)
      data
    end

    # Retrieve an Inquiry Template
    # Retrieves details of a specific Inquiry Template by ID.  Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like Inquiry Templates in Sandbox via API.
    # @param inquiry_template_id [String] Inquiry Template ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :key_inflection Determines casing for the API response.
    # @option opts [String] :idempotency_key Ensures the request is idempotent.
    # @option opts [ApiVersion] :persona_version 
    # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.
    # @option opts [Hash<String, String>] :fields Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.
    # @return [Array<(RetrieveAnInquiryTemplate200Response, Integer, Hash)>] RetrieveAnInquiryTemplate200Response data, response status code and response headers
    def retrieve_an_inquiry_template_with_http_info(inquiry_template_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: InquiryTemplatesApi.retrieve_an_inquiry_template ...'
      end
      # verify the required parameter 'inquiry_template_id' is set
      if @api_client.config.client_side_validation && inquiry_template_id.nil?
        fail ArgumentError, "Missing the required parameter 'inquiry_template_id' when calling InquiryTemplatesApi.retrieve_an_inquiry_template"
      end
      allowable_values = ["camel", "kebab", "snake"]
      if @api_client.config.client_side_validation && opts[:'key_inflection'] && !allowable_values.include?(opts[:'key_inflection'])
        fail ArgumentError, "invalid value for \"key_inflection\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/inquiry-templates/{inquiry-template-id}'.sub('{' + 'inquiry-template-id' + '}', CGI.escape(inquiry_template_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'include'] = opts[:'include'] if !opts[:'include'].nil?
      query_params[:'fields'] = opts[:'fields'] if !opts[:'fields'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'Key-Inflection'] = opts[:'key_inflection'] if !opts[:'key_inflection'].nil?
      header_params[:'Idempotency-Key'] = opts[:'idempotency_key'] if !opts[:'idempotency_key'].nil?
      header_params[:'Persona-Version'] = opts[:'persona_version'] if !opts[:'persona_version'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'RetrieveAnInquiryTemplate200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"InquiryTemplatesApi.retrieve_an_inquiry_template",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: InquiryTemplatesApi#retrieve_an_inquiry_template\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
